### ISSUE TITLE
Repository Structure

### ISSUE THREAD

**Issue by Sxtanna** [AmazonPriime/Simple-Kits#1]
- Your git repository is 1 directory too high.
- You are lacking a .gitignore file. Leaking your IDE files into the repository.

**Comment by Sxtanna** [comment]
An example of what your .gitignore file should look like.

```
# Gradle
.gradle/
build/
*out/

# IDEA
.idea/

# Allow gradle wrapper
!*gradle-wrapper.jar
```

**Comment by AmazonPriime** [comment]
Adding a .gitignore file in the next commit, thanks for the example structure.
