### ISSUE TITLE
Gradle Build File

### ISSUE THREAD

**Issue by Sxtanna** [AmazonPriime/Simple-Kits#2]
Your gradle file is using the legacy format for a couple of things.
-----
### Plugin block

Old plugin definition:
```
apply plugin: 'java'
```

New plugin definition:
```
plugins {
    id 'java'
}
```
-----
### Java Source/Target compatibility

Old string literal method:
```
sourceCompatibility = '1.8'
targetCompatibility = '1.8'
```

"New" enum method:
```
sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8
```

**Comment by AmazonPriime** [comment]
Thank you, updated the build file accordingly.
