### ISSUE TITLE
Spigot Repository Issue

### ISSUE THREAD

**Issue by Sxtanna** [AmazonPriime/Simple-Kits#3]
When using the spigot api you need to define two repositories for a single dependency, because the spigot devs are idiots and don't just put bungee in their repo.

You can simply replace these two:
```
maven {
    name = 'spigotmc-repo'
    url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
}
maven {
    name = 'sonatype'
    url = 'https://oss.sonatype.org/content/groups/public/'
}
```

With the singular repository provided by PaperMC:
```
maven {
    url = "https://papermc.io/repo/repository/maven-public/"
}
```

(a side note, you don't need to supply the name of the repository)

**Comment by AmazonPriime** [comment]
Thanks for the information, updating the repositories to use the PaperMC url instead.
